name: Deploy EKS via Terraform Cloud

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Upload the TF config to your TFC workspace
      - name: Upload configuration to TFC
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        with:
          organization: Poc05-Organization
          workspace: eks-terraform-tfc
          token: ${{ secrets.TFC_TOKEN }}

      # 2) Create an applyable run in TFC
      - name: Create applyable run
        id: run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        with:
          organization: Poc05-Organization
          workspace: eks-terraform-tfc
          token: ${{ secrets.TFC_TOKEN }}
          message: "Apply from push to main"

      # 3) Apply that run
      - name: Apply run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        with:
          organization: Poc05-Organization
          workspace: eks-terraform-tfc
          token: ${{ secrets.TFC_TOKEN }}
          run_id: ${{ steps.run.outputs.run_id }}
