name: Deploy EKS via Terraform Cloud

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Cloud Apply
        uses: dflook/terraform-cloud-apply@v1
        with:
          organization: Poc05-Organization          # <-- change
          workspace: eks-terraform-tfc            # <-- change
          api_token: ${{ secrets.TFC_TOKEN }}
          variables: |
            region=ap-south-1
            cluster_name=poc-eks-cluster
